server:
  port: 12000
spring:
  application:
    name: "gateway-service"
  data:
    redis:
      port: 6379
      host: localhost
  cloud:
    gateway:
      routes:
        - id: consumerService
          uri: lb://consumer-service
          predicates:
            - Path=/api/blogs/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: providerService
          uri: lb://provider-service
          predicates:
            - Path=/api/users/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false   # 注意：allowedOrigins为*时，allowCredentials必须为false
            maxAge: 3600
eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: TIME_BASED
        sliding-window-size: 5000
        waitDurationInOpenState: 5000 # 熔断器从打开到半开需要的时间
        failure-rate-threshold: 10  # 熔断器打开的失败阈值
        event-consumer-buffer-size: 5 #事件缓冲区大小
        automatic-transition-from-open-to-half-open-enabled: true # 是否自动从打开到半开
        recordExceptions: java.lang.Exception  # 记录的异常
        register-health-indicator: false # 健康监测
        minimum-number-of-calls: 1 #触发熔断机制的最⼩请求个数
        permitted-number-of-calls-in-half-open-state: 2 #HALF_OPEN状态的时候，允许通过的请求个数
    instances:
      backendA:
        base-config: default
      backendB:
        base-config: default
        wait-duration-in-open-state: 3000
        failure-rate-threshold: 15
  ratelimiter:
    instances:
      ratelimiterA:
        limit-for-period: 5         # 每个刷新周期最多允许5个请求
        limit-refresh-period: 2s    # 刷新周期为2秒
        timeout-duration: 1s